version: "3"
services:
  mongodb:
    image: mongo:5.0.5
    ports:
      - "27017:27017"
    volumes:
      - mongo_db_volume:/data/db
  book-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - spring.data.mongodb.host=mongodb
    depends_on:
      - mongodb
volumes:
    mongo_db_volume:
      driver: local